services:
  redis:
    image: redis:7.2.0
    ports:
      - "6379:6379"

  worker:
    build: .
    env_file:
      - .env
    command: celery -A app.worker_process worker --loglevel=info --concurrency=2
    depends_on:
      - redis
    environment:
        CELERY_BROKER_URL: "redis://redis:6379/0"
        CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./app/database/chroma_db/:/app/database/chroma_db
      - ./app/database/reviews.duckdb/:/app/database/reviews.duckdb

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    depends_on:
      - redis
      - worker
    environment:
        CELERY_BROKER_URL: "redis://redis:6379/0"
        CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./app/database/chroma_db/:/app/database/chroma_db
      - ./app/database/reviews.duckdb/:/app/database/reviews.duckdb
